name: industrial_app
description: Industrial AI App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  fl_chart: ^0.69.0

flutter:
  uses-material-design: true
