dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP requests (برای AI و API)
  http: ^1.2.2

  # نمودارها
  fl_chart: ^0.68.0

  # دیتابیس محلی (Offline Farm Storage)
  sqflite: ^2.3.3+1

  # مسیر فایل‌ها (برای SQLite)
  path: ^1.9.0

  # مدیریت state ساده (اختیاری ولی مفید برای داشبورد)
  provider: ^6.1.2
